version: '3.10-slim'

services:
  web:
    build: .
    container_name: fastapi_web
    volumes:
      - torch_cache:/root/.cache/torch
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      EXPRESS_API_URL: ${EXPRESS_API_URL}
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  torch_cache: